### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by Jonhug82** [Julusian/companion-remote#17] opened 2021-02-01 15:33 UTC
![Error](https://user-images.githubusercontent.com/67643240/106478617-48462180-64a1-11eb-8305-3b1cb65796d5.png)

I have seen this error come up a few times, not sure what is causing it.

**Comment by Julusian** [comment] 2021-02-01 15:40
Duplicate of #15 
I have a partial fix, but havent figured out the cause of this yet. It appears to be some data corruption in the stream from companion, but I don't know why yet

**Closed by Julusian** 2021-02-01 15:40 UTC

**Comment by Julusian** [comment] 2021-02-01 19:45
fixed https://github.com/Julusian/companion-remote/releases/tag/v0.2.2
